version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_curso_git
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: curso_git
    volumes:
      - mongo_data:/data/db                     # Volume persistente dos dados
      - ./mongo-init:/docker-entrypoint-initdb.d  # Script de inicialização

volumes:
  mongo_data:  # Volume nomeado persistente
